# Generated by Django 3.1.1 on 2021-03-21 17:46

import autoslug.fields
from django.db import migrations, models
import marinerbookings.bookings.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210309_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='booking_source',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='created',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='modified',
        ),
        migrations.AddField(
            model_name='guest',
            name='num_child',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'Enquiry'), (1, 'Acknowledged'), (2, 'Deposit Received'), (3, 'Balance Received'), (4, 'Keys Sent'), (5, 'Stay Complete')], default=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=marinerbookings.bookings.models.get_populate_from, unique=True),
        ),
    ]
