# Generated by Django 3.0.7 on 2020-06-28 17:00

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('guest_first_name', models.CharField(max_length=255, verbose_name='Guest first name')),
                ('guest_last_name', models.CharField(max_length=255, verbose_name='Guest last name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='guest_last_name', unique=True, verbose_name='Guest name')),
                ('booking_source', models.CharField(choices=[('unspecified', 'Unspecified'), ('airbnb', 'AirBnB'), ('mariners', 'Mariners'), ('friends', 'Friends'), ('owners', 'Owners')], default='unspecified', max_length=20, verbose_name='BookingSource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
