# Generated by Django 3.0.7 on 2020-07-08 14:58

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mariners3.guests.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_guest_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=mariners3.guests.models.get_populate_from),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('partner_first_name', models.CharField(max_length=255, verbose_name='Partner first name')),
                ('partner_last_name', models.CharField(max_length=255, verbose_name='Partner last name')),
                ('child_one', models.CharField(max_length=120, verbose_name='Child one')),
                ('child_two', models.CharField(max_length=120, verbose_name='Child two')),
                ('child_three', models.CharField(max_length=120, verbose_name='Child three')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_status', models.IntegerField(choices=[(0, 'Guest'), (1, 'Friend'), (2, 'Owners'), (3, 'Airbnb')], default=0, verbose_name='Guest status')),
                ('ack_date', models.DateField(verbose_name='Date acknowledged')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('dep_recd', models.DateField(blank=True, null=True, verbose_name='Deposit received')),
                ('bal_amount', models.IntegerField(default=0, verbose_name='Balance due')),
                ('dep_amount', models.IntegerField(default=0, verbose_name='Deposit amount')),
                ('sec_recd', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Separate Cheque'), (2, 'With Balance'), (3, 'Bacs'), (4, 'Not Required')], default=0, verbose_name='Security deposit')),
                ('bal_recd', models.DateField(blank=True, null=True, verbose_name='Balance received')),
                ('keys_sent', models.DateField(blank=True, null=True, verbose_name='Date keys sent')),
                ('sec_retn', models.DateField(blank=True, null=True, verbose_name='Security deposit returned')),
                ('rtm_sent', models.IntegerField(choices=[(0, 'Enquiry'), (1, 'Acknowledged'), (2, 'Deposit Received'), (3, 'Balance Received'), (4, 'Keys Sent'), (5, 'Stay Complete')], default=0, verbose_name='Status')),
                ('booking_notes', models.TextField(blank=True, verbose_name='Notes')),
                ('bkd_child', models.IntegerField(default=0, verbose_name='Children')),
                ('bkd_adult', models.IntegerField(default=2, verbose_name='Adults')),
                ('guest_one', models.CharField(blank=True, max_length=30, verbose_name='Guest 1')),
                ('guest_two', models.CharField(blank=True, max_length=30, verbose_name='Guest 2')),
                ('guest_three', models.CharField(blank=True, max_length=30, verbose_name='Guest 3')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guests.Guest')),
            ],
        ),
    ]
