# Generated by Django 3.0.7 on 2020-07-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20200708_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
