# Generated by Django 3.0.7 on 2020-07-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_land_line',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
