# Generated by Django 3.0.7 on 2020-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_auto_20200717_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='booking_source',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('airbnb', 'AirBnB'), ('mariners', 'Mariners'), ('friends', 'Friends'), ('owners', 'Owners')], default='unspecified', max_length=20, verbose_name='Booking Source'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_land_line',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Landline'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
    ]
