# Generated by Django 3.0.7 on 2020-10-23 12:42

import autoslug.fields
from django.db import migrations
import mariners3.guests.models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_auto_20200717_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=mariners3.guests.models.get_populate_from, unique=True),
        ),
    ]
